# define global variables for internal use
globalVariables(c(
  ".",
  ".data",
  "base_area",
  "base_prop",
  "base_siblings",
  "base_name",
  "base_overlap",
  "base_ID",
  "new_area",
  "new_prop",
  "targetID",
  "target_prop",
  "target_area",
  "amount",
  "col_name",
  "col_type",
  "description",
  "dup",
  "external",
  "externalID",
  "gazClass",
  "gazID",
  "gazID2",
  "gazMatch",
  "gazName",
  "geoID",
  "geom",
  "has_broader",
  "has_broader_match",
  "has_close_match",
  "has_exact_match",
  "has_narrower_match",
  "id",
  "intersect_area",
  "label",
  "len new_label",
  "new_name",
  "new_overlap",
  "outMatch",
  "outString",
  "parentID",
  "rn",
  "siblings",
  "source_overlap",
  "target_overlap",
  "tempID",
  "thisName",
  "unitCol",
  "new_label",
  "len"
))

.onAttach <- function(libname, pkgname){
  options(adb_testing = FALSE)
}